---
name: CI

on:
  push:
    branches: ["master"]
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - uses: pre-commit/action@v3.0.1

  tests:
    name: "Python ${{ matrix.python-version }}"
    runs-on: ${{ matrix.machine }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - python-version: "3.8"
            machine: ubuntu-22.04
          - python-version: "3.9"
            machine: ubuntu-22.04
          - python-version: "3.10"
            machine: ubuntu-22.04
          - python-version: "3.11"
            machine: ubuntu-22.04
          - python-version: "3.12"
            machine: ubuntu-22.04
          - python-version: "3.13"
            machine: ubuntu-22.04
    steps:
      - uses: "actions/checkout@v3"
      - uses: "actions/setup-python@v4"
        with:
          python-version: "${{ matrix.python-version }}"
      - name: "Install dependencies"
        run: |
          set -xe
          python -VV
          python -m site
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install --upgrade virtualenv tox tox-gh-actions
      - name: "Run tox targets for ${{ matrix.python-version }}"
        run: |
          python -m tox
      - uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          flags: unittests # optional
          verbose: true # optional (default = false)
